server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: yrO,cl:#x7y8
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath*:com/**/mapper/*.xml
